name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lerna publish from-git --dist-tag beta --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
